// Dataset Seeding Database PetaKarier (TypeScript Native)
// Seluruh data persisten bersumber langsung dari PostgreSQL Database

export interface SeedJenisUsaha {
  id: string;
  nama: string;
  kategori: string;
  emoji: string;
  icon: string;
  deskripsi: string;
  tags: string[];
  modalMin: number;
  modalMax: number;
  peralatan: number;
  bahanBakuBulanan: number;
  gajiKaryawan: number;
  promosiBulanan: number;
  revenueBulanan: number;
  marginBulanan: number;
  resiko: string;
  potensi: number;
  cocokUntuk: string;
}

export interface SeedKota {
  id: string;
  nama: string;
  provinsi: string;
  wilayah: string;
  umr: number;
  sewaTempat: number;
  utilitas: number;
  retribusi: number;
  latitude?: number;
  longitude?: number;
}

export const jenisUsahaSeedList: SeedJenisUsaha[] = [
  {
    "id": "makanan-rumahan",
    "nama": "Makanan Rumahan & Bento",
    "kategori": "Kuliner",
    "emoji": "UtensilsCrossed",
    "deskripsi": "Jualan masakan rumahan dengan sistem pre-order, rice bowl, atau jualan harian via WA & media sosial.",
    "tags": [
      "memasak",
      "manajemen-waktu",
      "sosial-media"
    ],
    "modalMin": 5000000,
    "modalMax": 15000000,
    "peralatan": 3500000,
    "bahanBakuBulanan": 2500000,
    "gajiKaryawan": 0,
    "promosiBulanan": 400000,
    "revenueBulanan": 8500000,
    "marginBulanan": 3200000,
    "resiko": "Kompetisi tinggi dengan warung makan & katering besar",
    "potensi": 4,
    "cocokUntuk": "Pemula yang suka memasak dan punya dapur di rumah",
    "icon": "UtensilsCrossed"
  },
  {
    "id": "katering-rumahan",
    "nama": "Katering Nasi Box & Event",
    "kategori": "Kuliner",
    "emoji": "Utensils",
    "deskripsi": "Catering harian (nasi box) untuk kantor, acara, dan komunitas dengan sistem langganan.",
    "tags": [
      "memasak",
      "negosiasi",
      "manajemen-waktu"
    ],
    "modalMin": 8000000,
    "modalMax": 25000000,
    "peralatan": 5000000,
    "bahanBakuBulanan": 4000000,
    "gajiKaryawan": 0,
    "promosiBulanan": 600000,
    "revenueBulanan": 12000000,
    "marginBulanan": 4500000,
    "resiko": "Bergantung pada kontrak langganan; kualitas harus konsisten",
    "potensi": 5,
    "cocokUntuk": "Mereka yang punya jaringan kantor/komunitas",
    "icon": "Utensils"
  },
  {
    "id": "kedai-kopi",
    "nama": "Kedai Kopi & Minuman Kekinian",
    "kategori": "Kuliner",
    "emoji": "Coffee",
    "deskripsi": "Kedai kopi dengan konsep minimalis, take-away & dine-in skala kecil.",
    "tags": [
      "peracik-kopi",
      "desain",
      "sosial-media"
    ],
    "modalMin": 15000000,
    "modalMax": 40000000,
    "peralatan": 12000000,
    "bahanBakuBulanan": 3000000,
    "gajiKaryawan": 1500000,
    "promosiBulanan": 800000,
    "revenueBulanan": 15000000,
    "marginBulanan": 6000000,
    "resiko": "Modal besar; tren kopi fluktuatif",
    "potensi": 4,
    "cocokUntuk": "Pecinta kopi yang siap komitmen penuh",
    "icon": "Coffee"
  },
  {
    "id": "frozen-food",
    "nama": "Distribusi Frozen Food Rumahan",
    "kategori": "Kuliner",
    "emoji": "PackageCheck",
    "deskripsi": "Produksi & distribusi frozen food (dumpling, nugget rumahan) ke warung, minimarket, dan reseller.",
    "tags": [
      "memasak",
      "logistik",
      "kemasan"
    ],
    "modalMin": 12000000,
    "modalMax": 30000000,
    "peralatan": 8000000,
    "bahanBakuBulanan": 5000000,
    "gajiKaryawan": 1000000,
    "promosiBulanan": 700000,
    "revenueBulanan": 15000000,
    "marginBulanan": 4800000,
    "resiko": "Butuh freezer & manajemen rantai dingin",
    "potensi": 4,
    "cocokUntuk": "Orang dengan jiwa logistik & produksi",
    "icon": "PackageCheck"
  },
  {
    "id": "distro-thrift",
    "nama": "Distro & Thrift Terkurasi",
    "kategori": "Fashion",
    "emoji": "Shirt",
    "deskripsi": "Jualan pakaian thrift & lokal dengan kurasi ketat lewat toko online dan pop-up store.",
    "tags": [
      "fashion",
      "foto-produk",
      "sosial-media"
    ],
    "modalMin": 10000000,
    "modalMax": 30000000,
    "peralatan": 6000000,
    "bahanBakuBulanan": 5000000,
    "gajiKaryawan": 500000,
    "promosiBulanan": 700000,
    "revenueBulanan": 14000000,
    "marginBulanan": 4500000,
    "resiko": "Stok thrift tidak selalu konsisten; tren berubah cepat",
    "potensi": 4,
    "cocokUntuk": "Anak muda yang paham tren fashion",
    "icon": "Shirt"
  },
  {
    "id": "custom-merch",
    "nama": "Custom Merch & Sablon Kaos",
    "kategori": "Fashion",
    "emoji": "Palette",
    "deskripsi": "Jasa sablon, bordir, dan pembuatan merchandise custom untuk komunitas, sekolah, dan acara.",
    "tags": [
      "desain",
      "sablon",
      "sosial-media"
    ],
    "modalMin": 12000000,
    "modalMax": 30000000,
    "peralatan": 9000000,
    "bahanBakuBulanan": 3000000,
    "gajiKaryawan": 500000,
    "promosiBulanan": 600000,
    "revenueBulanan": 12000000,
    "marginBulanan": 4800000,
    "resiko": "Mesin butuh perawatan; order musiman",
    "potensi": 4,
    "cocokUntuk": "Kreatif yang senang pesanan custom",
    "icon": "Palette"
  },
  {
    "id": "hijab-modest-wear",
    "nama": "Brand Hijab & Modest Wear",
    "kategori": "Fashion",
    "emoji": "Sparkles",
    "deskripsi": "Produksi dan penjualan jilbab motif printing, gamis harian, dan aksesori modest fashion via marketplace & live shopping.",
    "tags": [
      "fashion",
      "foto-produk",
      "desain",
      "sosial-media"
    ],
    "modalMin": 8000000,
    "modalMax": 25000000,
    "peralatan": 5000000,
    "bahanBakuBulanan": 4000000,
    "gajiKaryawan": 0,
    "promosiBulanan": 800000,
    "revenueBulanan": 14000000,
    "marginBulanan": 5500000,
    "resiko": "Perputaran model fashion muslim yang cepat setiap musim",
    "potensi": 5,
    "cocokUntuk": "Pecinta fashion muslimah yang mengerti selera pasar wanita muda",
    "icon": "Sparkles"
  },
  {
    "id": "sepatu-tas-handmade",
    "nama": "Pengrajin Tas & Sepatu Lokal",
    "kategori": "Fashion",
    "emoji": "ShoppingBag",
    "deskripsi": "Produksi tas kanvas, totebag, dan sepatu kasual lokal dengan desain minimalis estetik.",
    "tags": [
      "fashion",
      "desain",
      "foto-produk",
      "sosial-media"
    ],
    "modalMin": 9000000,
    "modalMax": 28000000,
    "peralatan": 6500000,
    "bahanBakuBulanan": 3500000,
    "gajiKaryawan": 0,
    "promosiBulanan": 700000,
    "revenueBulanan": 13000000,
    "marginBulanan": 5200000,
    "resiko": "Kualitas bahan baku dan ketahanan jahitan harus teruji",
    "potensi": 4,
    "cocokUntuk": "Wirausaha yang menyukai desain produk aksesori dan fashion",
    "icon": "ShoppingBag"
  },
  {
    "id": "desain-grafis",
    "nama": "Studio Desain Grafis & Branding",
    "kategori": "Kreatif",
    "emoji": "Brush",
    "deskripsi": "Jasa desain logo, feed sosial media, dan brand identity untuk UMKM & personal brand.",
    "tags": [
      "desain",
      "fotografi",
      "teknologi"
    ],
    "modalMin": 8000000,
    "modalMax": 20000000,
    "peralatan": 12000000,
    "bahanBakuBulanan": 500000,
    "gajiKaryawan": 0,
    "promosiBulanan": 500000,
    "revenueBulanan": 10000000,
    "marginBulanan": 6500000,
    "resiko": "Pendapatan bergantung proyek & jam terbang",
    "potensi": 5,
    "cocokUntuk": "Anak kreatif yang jago visual",
    "icon": "Brush"
  },
  {
    "id": "content-creator",
    "nama": "Studio Konten & Live Streamer",
    "kategori": "Kreatif",
    "emoji": "Smartphone",
    "deskripsi": "Bikin konten media sosial, video promosi TikTok/Reels, dan live hosting produk UMKM.",
    "tags": [
      "sosial-media",
      "editing-video",
      "public-speaking"
    ],
    "modalMin": 10000000,
    "modalMax": 25000000,
    "peralatan": 15000000,
    "bahanBakuBulanan": 1000000,
    "gajiKaryawan": 0,
    "promosiBulanan": 800000,
    "revenueBulanan": 12000000,
    "marginBulanan": 7000000,
    "resiko": "Penghasilan fluktuatif; butuh konsistensi konten",
    "potensi": 4,
    "cocokUntuk": "Ekspresif, suka tampil di depan kamera",
    "icon": "Smartphone"
  },
  {
    "id": "fotografi-videografi",
    "nama": "Fotografi & Videografi Komersial",
    "kategori": "Kreatif",
    "emoji": "Camera",
    "deskripsi": "Jasa foto katalog produk UMKM, video company profile, dan dokumentasi event.",
    "tags": [
      "fotografi",
      "editing-video",
      "desain"
    ],
    "modalMin": 15000000,
    "modalMax": 35000000,
    "peralatan": 18000000,
    "bahanBakuBulanan": 500000,
    "gajiKaryawan": 0,
    "promosiBulanan": 700000,
    "revenueBulanan": 13000000,
    "marginBulanan": 8000000,
    "resiko": "Persaingan ketat; butuh portofolio kuat",
    "potensi": 4,
    "cocokUntuk": "Punya kamera & sense of art tinggi",
    "icon": "Camera"
  },
  {
    "id": "kerajinan-souvenir",
    "nama": "Kerajinan Souvenir & Hadiah Custom",
    "kategori": "Kreatif",
    "emoji": "Gift",
    "deskripsi": "Produksi kerajinan resin, hampers akrilik, dan plakat souvenir wisuda & pernikahan.",
    "tags": [
      "desain",
      "kemasan",
      "foto-produk",
      "sosial-media"
    ],
    "modalMin": 6000000,
    "modalMax": 18000000,
    "peralatan": 5000000,
    "bahanBakuBulanan": 2000000,
    "gajiKaryawan": 0,
    "promosiBulanan": 500000,
    "revenueBulanan": 9500000,
    "marginBulanan": 4500000,
    "resiko": "Pesanan bersifat musiman (musim wisuda / nikah)",
    "potensi": 4,
    "cocokUntuk": "Orang yang telaten dan menyukai kerajinan tangan",
    "icon": "Gift"
  },
  {
    "id": "jasa-web-digital",
    "nama": "Agensi Web & Software House",
    "kategori": "Digital",
    "emoji": "Laptop",
    "deskripsi": "Jasa pembuatan website toko online, aplikasi landing page, dan sistem inventori UMKM.",
    "tags": [
      "teknologi",
      "desain",
      "negosiasi"
    ],
    "modalMin": 10000000,
    "modalMax": 35000000,
    "peralatan": 15000000,
    "bahanBakuBulanan": 1000000,
    "gajiKaryawan": 1500000,
    "promosiBulanan": 800000,
    "revenueBulanan": 18000000,
    "marginBulanan": 9500000,
    "resiko": "Persaingan global; butuh update keahlian IT berkelanjutan",
    "potensi": 5,
    "cocokUntuk": "Talenta IT & desainer digital berpengalaman",
    "icon": "Laptop"
  },
  {
    "id": "social-media-agency",
    "nama": "Agensi Kelola Medsos & Ads",
    "kategori": "Digital",
    "emoji": "BarChart3",
    "deskripsi": "Layanan manajemen konten feeds, copywriting, TikTok live host, dan periklanan digital untuk UMKM lokal.",
    "tags": [
      "sosial-media",
      "desain",
      "editing-video",
      "negosiasi"
    ],
    "modalMin": 6000000,
    "modalMax": 20000000,
    "peralatan": 8000000,
    "bahanBakuBulanan": 800000,
    "gajiKaryawan": 1000000,
    "promosiBulanan": 700000,
    "revenueBulanan": 15000000,
    "marginBulanan": 7500000,
    "resiko": "Retensi klien berbasis hasil performa kampanye iklan",
    "potensi": 5,
    "cocokUntuk": "Generasi muda yang aktif tren media sosial & strategi pemasaran digital",
    "icon": "BarChart3"
  },
  {
    "id": "servis-gadget-it",
    "nama": "Servis Gadget, HP & IT Support",
    "kategori": "Digital",
    "emoji": "Wrench",
    "deskripsi": "Jasa perbaikan smartphone, laptop, instalasi jaringan WiFi kantor, dan instalasi software UMKM.",
    "tags": [
      "teknologi",
      "pelayanan",
      "ketelitian",
      "teknik"
    ],
    "modalMin": 8000000,
    "modalMax": 25000000,
    "peralatan": 9000000,
    "bahanBakuBulanan": 2000000,
    "gajiKaryawan": 0,
    "promosiBulanan": 500000,
    "revenueBulanan": 13000000,
    "marginBulanan": 6200000,
    "resiko": "Ketersediaan sparepart dan risiko kerusakan komponen saat servis",
    "potensi": 4,
    "cocokUntuk": "Teknisi handal yang menyukai hardware & troubleshooting",
    "icon": "Wrench"
  },
  {
    "id": "kursus-coding-it",
    "nama": "Bootcamp Coding & AI Pemula",
    "kategori": "Digital",
    "emoji": "Rocket",
    "deskripsi": "Kursus kilat pembuatan website, otomatisasi AI untuk bisnis, dan pengenalan tools digital bagi pemula.",
    "tags": [
      "teknologi",
      "public-speaking",
      "manajemen-waktu"
    ],
    "modalMin": 7000000,
    "modalMax": 22000000,
    "peralatan": 8000000,
    "bahanBakuBulanan": 500000,
    "gajiKaryawan": 0,
    "promosiBulanan": 800000,
    "revenueBulanan": 14000000,
    "marginBulanan": 8000000,
    "resiko": "Kurikulum harus selalu up-to-date mengikuti tren AI & tech",
    "potensi": 5,
    "cocokUntuk": "Programmer & tech enthusiast yang gemar mengajar",
    "icon": "Rocket"
  },
  {
    "id": "barbershop-salon",
    "nama": "Barbershop & Studio Grooming",
    "kategori": "Kecantikan",
    "emoji": "Scissors",
    "deskripsi": "Layanan cukur pria modern, perawatan rambut, dan grooming pria/wanita dengan tempat nyaman.",
    "tags": [
      "pelayanan",
      "ketelitian",
      "sosial-media"
    ],
    "modalMin": 18000000,
    "modalMax": 45000000,
    "peralatan": 16000000,
    "bahanBakuBulanan": 2500000,
    "gajiKaryawan": 2000000,
    "promosiBulanan": 700000,
    "revenueBulanan": 16000000,
    "marginBulanan": 6800000,
    "resiko": "Pentingnya skill kapster/hairstylist & sewa lokasi strategis",
    "potensi": 4,
    "cocokUntuk": "Wirausaha yang menyukai bisnis jasa gaya hidup & grooming",
    "icon": "Scissors"
  },
  {
    "id": "nail-art-eyelash",
    "nama": "Studio Nail Art & Eyelash",
    "kategori": "Kecantikan",
    "emoji": "Sparkles",
    "deskripsi": "Layanan perawatan kuku estetika, nail art motif modern, dan eyelash extension dengan opsi studio atau home service.",
    "tags": [
      "pelayanan",
      "ketelitian",
      "desain",
      "sosial-media"
    ],
    "modalMin": 7000000,
    "modalMax": 22000000,
    "peralatan": 6000000,
    "bahanBakuBulanan": 1500000,
    "gajiKaryawan": 0,
    "promosiBulanan": 600000,
    "revenueBulanan": 13000000,
    "marginBulanan": 6500000,
    "resiko": "Ketelitian tinggi dan kepuasan estetika pelanggan yang spesifik",
    "potensi": 5,
    "cocokUntuk": "Wirausaha yang memiliki ketelitian tangan & minat industri kecantikan",
    "icon": "Sparkles"
  },
  {
    "id": "distributor-skincare",
    "nama": "Reseller Skincare & Kosmetik BPOM",
    "kategori": "Kecantikan",
    "emoji": "Heart",
    "deskripsi": "Penjualan paket skincare lokal berizin BPOM melalui live streaming TikTok, Shopee, dan jaringan reseller.",
    "tags": [
      "sosial-media",
      "foto-produk",
      "negosiasi",
      "pelayanan"
    ],
    "modalMin": 6000000,
    "modalMax": 20000000,
    "peralatan": 3000000,
    "bahanBakuBulanan": 6000000,
    "gajiKaryawan": 0,
    "promosiBulanan": 800000,
    "revenueBulanan": 15000000,
    "marginBulanan": 5500000,
    "resiko": "Kompetisi harga antar reseller online yang ketat",
    "potensi": 4,
    "cocokUntuk": "Aktif di media sosial & memiliki kemampuan persuasif",
    "icon": "Heart"
  },
  {
    "id": "spa-pijat-relaksasi",
    "nama": "Homecare Spa & Pijat Relaksasi",
    "kategori": "Kecantikan",
    "emoji": "Smile",
    "deskripsi": "Jasa pijat refleksi, lulur tradisional, dan aromaterapi panggilan untuk ibu & keluarga di rumah.",
    "tags": [
      "pelayanan",
      "ketelitian",
      "manajemen-waktu"
    ],
    "modalMin": 5000000,
    "modalMax": 15000000,
    "peralatan": 4000000,
    "bahanBakuBulanan": 1200000,
    "gajiKaryawan": 0,
    "promosiBulanan": 400000,
    "revenueBulanan": 9000000,
    "marginBulanan": 5000000,
    "resiko": "Keahlian terapis harus bersertifikat & membangun kepercayaan",
    "potensi": 4,
    "cocokUntuk": "Terapis berpengalaman yang ingin membuka usaha mandiri",
    "icon": "Smile"
  },
  {
    "id": "bimbel-kursus-skill",
    "nama": "Akademi Bimbel & Kursus Skill",
    "kategori": "Pendidikan",
    "emoji": "BookOpen",
    "deskripsi": "Bimbingan belajar intensif dan pelatihan keterampilan khusus (bahasa asing, coding, musik).",
    "tags": [
      "public-speaking",
      "ketelitian",
      "manajemen-waktu"
    ],
    "modalMin": 8000000,
    "modalMax": 25000000,
    "peralatan": 6000000,
    "bahanBakuBulanan": 800000,
    "gajiKaryawan": 1000000,
    "promosiBulanan": 500000,
    "revenueBulanan": 11000000,
    "marginBulanan": 5200000,
    "resiko": "Ketersediaan pengajar berkualitas; siklus tahun ajaran baru",
    "potensi": 4,
    "cocokUntuk": "Pendidik & praktisi yang ingin berbagi pengetahuan",
    "icon": "BookOpen"
  },
  {
    "id": "daycare-anak",
    "nama": "Daycare & Rumah Belajar Anak",
    "kategori": "Pendidikan",
    "emoji": "Baby",
    "deskripsi": "Pusat penitipan anak edukatif dan kelas sensorik balita bagi orang tua pekerja dengan lingkungan aman dan ramah.",
    "tags": [
      "public-speaking",
      "pelayanan",
      "ketelitian",
      "manajemen-waktu"
    ],
    "modalMin": 15000000,
    "modalMax": 40000000,
    "peralatan": 12000000,
    "bahanBakuBulanan": 2000000,
    "gajiKaryawan": 2000000,
    "promosiBulanan": 600000,
    "revenueBulanan": 16000000,
    "marginBulanan": 6000000,
    "resiko": "Tanggung jawab keselamatan anak tinggi & standar higienitas ketat",
    "potensi": 4,
    "cocokUntuk": "Tenaga pendidik PAUD atau wirausaha yang mencintai dunia anak",
    "icon": "Baby"
  },
  {
    "id": "kursus-baking-masak",
    "nama": "Studio Kursus Baking & Masak",
    "kategori": "Pendidikan",
    "emoji": "ChefHat",
    "deskripsi": "Kelas privat & workshop akhir pekan pembuatan kue kering, pastry, dan masakan khas nusantara.",
    "tags": [
      "memasak",
      "public-speaking",
      "kemasan",
      "foto-produk"
    ],
    "modalMin": 10000000,
    "modalMax": 28000000,
    "peralatan": 10000000,
    "bahanBakuBulanan": 2500000,
    "gajiKaryawan": 0,
    "promosiBulanan": 700000,
    "revenueBulanan": 13000000,
    "marginBulanan": 6000000,
    "resiko": "Perlu inovasi resep baru dan variasi menu kekinian",
    "potensi": 4,
    "cocokUntuk": "Chef, baker rumahan, atau pegiat kuliner yang komunikatif",
    "icon": "ChefHat"
  },
  {
    "id": "kursus-bahasa-asing",
    "nama": "Kursus Bahasa Asing & TOEFL",
    "kategori": "Pendidikan",
    "emoji": "Languages",
    "deskripsi": "Kelas intensif persiapan TOEFL/IELTS, Bahasa Inggris percakapan, dan Bahasa Jepang online/offline.",
    "tags": [
      "public-speaking",
      "teknologi",
      "manajemen-waktu"
    ],
    "modalMin": 5000000,
    "modalMax": 16000000,
    "peralatan": 5000000,
    "bahanBakuBulanan": 500000,
    "gajiKaryawan": 0,
    "promosiBulanan": 600000,
    "revenueBulanan": 10000000,
    "marginBulanan": 5500000,
    "resiko": "Persaingan dengan aplikasi belajar mandiri",
    "potensi": 4,
    "cocokUntuk": "Lulusan sastra atau pengajar bahasa berpengalaman",
    "icon": "Languages"
  },
  {
    "id": "laundry-kiloan",
    "nama": "Laundry Kiloan & Dry Clean",
    "kategori": "Jasa",
    "emoji": "Shirt",
    "deskripsi": "Jasa cuci setrika kiloan dengan sistem antar-jemput dan layanan express.",
    "tags": [
      "ketelitian",
      "manajemen-waktu",
      "pelayanan"
    ],
    "modalMin": 15000000,
    "modalMax": 35000000,
    "peralatan": 15000000,
    "bahanBakuBulanan": 1500000,
    "gajiKaryawan": 1000000,
    "promosiBulanan": 500000,
    "revenueBulanan": 12000000,
    "marginBulanan": 5500000,
    "resiko": "Boros listrik & air; musiman sepi di hari libur",
    "potensi": 4,
    "cocokUntuk": "Teliti & konsisten, cocok di area padat penduduk",
    "icon": "Shirt"
  },
  {
    "id": "cuci-steam",
    "nama": "Cuci Steam Motor & Mobil",
    "kategori": "Jasa",
    "emoji": "Bike",
    "deskripsi": "Jasa cuci motor steam + poles, cocok di dekat kost, kampus, atau pemukiman padat.",
    "tags": [
      "ketelitian",
      "pelayanan",
      "teknik"
    ],
    "modalMin": 10000000,
    "modalMax": 25000000,
    "peralatan": 10000000,
    "bahanBakuBulanan": 1200000,
    "gajiKaryawan": 1200000,
    "promosiBulanan": 400000,
    "revenueBulanan": 11000000,
    "marginBulanan": 5000000,
    "resiko": "Butuh lokasi strategis & air yang cukup",
    "potensi": 3,
    "cocokUntuk": "Suka hal praktis & bertemu banyak orang",
    "icon": "Bike"
  },
  {
    "id": "jastip",
    "nama": "Jasa Titip (Jastip) & Shopper",
    "kategori": "Jasa",
    "emoji": "ShoppingBag",
    "deskripsi": "Jastip makanan/barang dari luar kota atau event besar dengan sistem fee per item.",
    "tags": [
      "sosial-media",
      "negosiasi",
      "manajemen-waktu"
    ],
    "modalMin": 3000000,
    "modalMax": 10000000,
    "peralatan": 2000000,
    "bahanBakuBulanan": 3000000,
    "gajiKaryawan": 0,
    "promosiBulanan": 400000,
    "revenueBulanan": 7000000,
    "marginBulanan": 2800000,
    "resiko": "Terbatas oleh kapasitas & kepercayaan pelanggan",
    "potensi": 3,
    "cocokUntuk": "Punya mobilitas tinggi & jaringan luas",
    "icon": "ShoppingBag"
  },
  {
    "id": "les-privat",
    "nama": "Les Privat & Bimbingan Belajar",
    "kategori": "Jasa",
    "emoji": "GraduationCap",
    "deskripsi": "Bimbel kecil & les privat untuk siswa SD–SMA, tatap muka atau online.",
    "tags": [
      "public-speaking",
      "teknologi",
      "pelayanan"
    ],
    "modalMin": 3000000,
    "modalMax": 8000000,
    "peralatan": 3000000,
    "bahanBakuBulanan": 300000,
    "gajiKaryawan": 0,
    "promosiBulanan": 300000,
    "revenueBulanan": 6000000,
    "marginBulanan": 4000000,
    "resiko": "Butuh kompetensi & reputasi; jumlah murid fluktuatif",
    "potensi": 4,
    "cocokUntuk": "Pintar menjelaskan & sabar mengajar",
    "icon": "GraduationCap"
  },
  {
    "id": "hidroponik",
    "nama": "Urban Farming Hidroponik",
    "kategori": "Agribisnis",
    "emoji": "Sprout",
    "deskripsi": "Tanam sayur hidroponik & jual ke pasar, restoran, atau langganan rumah tangga.",
    "tags": [
      "berkebun",
      "teknologi",
      "riset"
    ],
    "modalMin": 6000000,
    "modalMax": 20000000,
    "peralatan": 8000000,
    "bahanBakuBulanan": 1500000,
    "gajiKaryawan": 0,
    "promosiBulanan": 400000,
    "revenueBulanan": 9000000,
    "marginBulanan": 4500000,
    "resiko": "Panas & hama memengaruhi hasil panen",
    "potensi": 4,
    "cocokUntuk": "Penyuka alam & punya lahan terbatas",
    "icon": "Sprout"
  },
  {
    "id": "budidaya-jamur",
    "nama": "Budidaya Jamur Tiram & Olahan",
    "kategori": "Agribisnis",
    "emoji": "Trees",
    "deskripsi": "Produksi jamur tiram segar dan aneka camilan keripik jamur untuk pasokan pasar serta reseller online.",
    "tags": [
      "berkebun",
      "kemasan",
      "logistik",
      "memasak"
    ],
    "modalMin": 5000000,
    "modalMax": 16000000,
    "peralatan": 4500000,
    "bahanBakuBulanan": 2000000,
    "gajiKaryawan": 0,
    "promosiBulanan": 350000,
    "revenueBulanan": 8500000,
    "marginBulanan": 4200000,
    "resiko": "Kelembapan dan kebersihan kumbung jamur harus dikontrol rutin",
    "potensi": 4,
    "cocokUntuk": "Pemula agribisnis dengan lahan pekarangan atau gudang kecil",
    "icon": "Trees"
  },
  {
    "id": "tanaman-hias-kebun",
    "nama": "Tanaman Hias & Lanskap Mini",
    "kategori": "Agribisnis",
    "emoji": "Flower2",
    "deskripsi": "Budidaya tanaman hias monstera, aglaonema, kaktus mini, dan jasa pembuatan taman vertikal rumah.",
    "tags": [
      "berkebun",
      "foto-produk",
      "pelayanan",
      "desain"
    ],
    "modalMin": 5000000,
    "modalMax": 18000000,
    "peralatan": 4000000,
    "bahanBakuBulanan": 1500000,
    "gajiKaryawan": 0,
    "promosiBulanan": 450000,
    "revenueBulanan": 8500000,
    "marginBulanan": 4200000,
    "resiko": "Perawatan tanaman sensitif cuaca dan hama daun",
    "potensi": 4,
    "cocokUntuk": "Pecinta tanaman dan estetika ruang hijau",
    "icon": "Flower2"
  },
  {
    "id": "ternak-madu-lebah",
    "nama": "Peternakan Lebah Madu Klanceng",
    "kategori": "Agribisnis",
    "emoji": "Bug",
    "deskripsi": "Budi daya lebah madu tanpa sengat (Trigona/Klanceng) ramah pemukiman dengan nilai jual madu tinggi.",
    "tags": [
      "berkebun",
      "kemasan",
      "logistik"
    ],
    "modalMin": 6000000,
    "modalMax": 20000000,
    "peralatan": 5500000,
    "bahanBakuBulanan": 1000000,
    "gajiKaryawan": 0,
    "promosiBulanan": 400000,
    "revenueBulanan": 9000000,
    "marginBulanan": 5000000,
    "resiko": "Ketersediaan vegetasi bunga pakan lebah di sekitar lokasi",
    "potensi": 5,
    "cocokUntuk": "Wirausaha agribisnis yang ingin produk bernilai jual tinggi",
    "icon": "Bug"
  }
];

export const kotaSeedList: SeedKota[] = [
  {
    "id": "aceh",
    "nama": "Aceh",
    "provinsi": "Aceh",
    "wilayah": "Sumatera",
    "umr": 3460672,
    "sewaTempat": 700000,
    "utilitas": 300000,
    "retribusi": 70000,
    "latitude": 5.5483,
    "longitude": 95.3238
  },
  {
    "id": "sumatera-utara",
    "nama": "Sumatera Utara",
    "provinsi": "Sumatera Utara",
    "wilayah": "Sumatera",
    "umr": 2809915,
    "sewaTempat": 800000,
    "utilitas": 380000,
    "retribusi": 75000,
    "latitude": 2.1154,
    "longitude": 99.5451
  },
  {
    "id": "sumatera-barat",
    "nama": "Sumatera Barat",
    "provinsi": "Sumatera Barat",
    "wilayah": "Sumatera",
    "umr": 2811000,
    "sewaTempat": 750000,
    "utilitas": 350000,
    "retribusi": 70000,
    "latitude": -0.7399,
    "longitude": 100.8
  },
  {
    "id": "riau",
    "nama": "Riau",
    "provinsi": "Riau",
    "wilayah": "Sumatera",
    "umr": 3294625,
    "sewaTempat": 900000,
    "utilitas": 400000,
    "retribusi": 80000,
    "latitude": 0.2933,
    "longitude": 101.7068
  },
  {
    "id": "kepulauan-riau",
    "nama": "Kepulauan Riau",
    "provinsi": "Kepulauan Riau",
    "wilayah": "Sumatera",
    "umr": 3402492,
    "sewaTempat": 950000,
    "utilitas": 420000,
    "retribusi": 85000,
    "latitude": 1.0456,
    "longitude": 103.745
  },
  {
    "id": "jambi",
    "nama": "Jambi",
    "provinsi": "Jambi",
    "wilayah": "Sumatera",
    "umr": 3037121,
    "sewaTempat": 750000,
    "utilitas": 350000,
    "retribusi": 70000,
    "latitude": -1.4852,
    "longitude": 102.4381
  },
  {
    "id": "sumatera-selatan",
    "nama": "Sumatera Selatan",
    "provinsi": "Sumatera Selatan",
    "wilayah": "Sumatera",
    "umr": 3456874,
    "sewaTempat": 800000,
    "utilitas": 370000,
    "retribusi": 75000,
    "latitude": -3.3194,
    "longitude": 104.9149
  },
  {
    "id": "bangka-belitung",
    "nama": "Bangka Belitung",
    "provinsi": "Bangka Belitung",
    "wilayah": "Sumatera",
    "umr": 3640000,
    "sewaTempat": 800000,
    "utilitas": 370000,
    "retribusi": 75000,
    "latitude": -2.741,
    "longitude": 106.4405
  },
  {
    "id": "bengkulu",
    "nama": "Bengkulu",
    "provinsi": "Bengkulu",
    "wilayah": "Sumatera",
    "umr": 2507079,
    "sewaTempat": 650000,
    "utilitas": 300000,
    "retribusi": 60000,
    "latitude": -3.5778,
    "longitude": 102.3463
  },
  {
    "id": "lampung",
    "nama": "Lampung",
    "provinsi": "Lampung",
    "wilayah": "Sumatera",
    "umr": 2716497,
    "sewaTempat": 700000,
    "utilitas": 320000,
    "retribusi": 65000,
    "latitude": -4.5586,
    "longitude": 105.4068
  },
  {
    "id": "dki-jakarta",
    "nama": "DKI Jakarta",
    "provinsi": "DKI Jakarta",
    "wilayah": "Jawa",
    "umr": 5067381,
    "sewaTempat": 1500000,
    "utilitas": 600000,
    "retribusi": 150000,
    "latitude": -6.2088,
    "longitude": 106.8456
  },
  {
    "id": "jawa-barat",
    "nama": "Jawa Barat",
    "provinsi": "Jawa Barat",
    "wilayah": "Jawa",
    "umr": 2101000,
    "sewaTempat": 950000,
    "utilitas": 400000,
    "retribusi": 90000,
    "latitude": -6.9175,
    "longitude": 107.6191
  },
  {
    "id": "jawa-tengah",
    "nama": "Jawa Tengah",
    "provinsi": "Jawa Tengah",
    "wilayah": "Jawa",
    "umr": 2036947,
    "sewaTempat": 800000,
    "utilitas": 350000,
    "retribusi": 80000,
    "latitude": -7.1509,
    "longitude": 110.1403
  },
  {
    "id": "diy",
    "nama": "DI Yogyakarta",
    "provinsi": "DI Yogyakarta",
    "wilayah": "Jawa",
    "umr": 2159000,
    "sewaTempat": 750000,
    "utilitas": 300000,
    "retribusi": 60000,
    "latitude": -7.7956,
    "longitude": 110.3695
  },
  {
    "id": "jawa-timur",
    "nama": "Jawa Timur",
    "provinsi": "Jawa Timur",
    "wilayah": "Jawa",
    "umr": 2165244,
    "sewaTempat": 900000,
    "utilitas": 400000,
    "retribusi": 85000,
    "latitude": -7.5361,
    "longitude": 112.2384
  },
  {
    "id": "banten",
    "nama": "Banten",
    "provinsi": "Banten",
    "wilayah": "Jawa",
    "umr": 2727812,
    "sewaTempat": 1100000,
    "utilitas": 450000,
    "retribusi": 100000,
    "latitude": -6.4058,
    "longitude": 106.064
  },
  {
    "id": "bali",
    "nama": "Bali",
    "provinsi": "Bali",
    "wilayah": "Nusa Tenggara",
    "umr": 2713672,
    "sewaTempat": 1200000,
    "utilitas": 500000,
    "retribusi": 100000,
    "latitude": -8.4095,
    "longitude": 115.1889
  },
  {
    "id": "ntb",
    "nama": "Nusa Tenggara Barat",
    "provinsi": "Nusa Tenggara Barat",
    "wilayah": "Nusa Tenggara",
    "umr": 2371407,
    "sewaTempat": 650000,
    "utilitas": 300000,
    "retribusi": 60000,
    "latitude": -8.6529,
    "longitude": 117.3616
  },
  {
    "id": "ntt",
    "nama": "Nusa Tenggara Timur",
    "provinsi": "Nusa Tenggara Timur",
    "wilayah": "Nusa Tenggara",
    "umr": 2186826,
    "sewaTempat": 600000,
    "utilitas": 280000,
    "retribusi": 55000,
    "latitude": -8.5569,
    "longitude": 120.6926
  },
  {
    "id": "kalimantan-barat",
    "nama": "Kalimantan Barat",
    "provinsi": "Kalimantan Barat",
    "wilayah": "Kalimantan",
    "umr": 2702616,
    "sewaTempat": 750000,
    "utilitas": 350000,
    "retribusi": 70000,
    "latitude": -0.0263,
    "longitude": 109.3425
  },
  {
    "id": "kalimantan-tengah",
    "nama": "Kalimantan Tengah",
    "provinsi": "Kalimantan Tengah",
    "wilayah": "Kalimantan",
    "umr": 3261616,
    "sewaTempat": 800000,
    "utilitas": 380000,
    "retribusi": 75000,
    "latitude": -1.6815,
    "longitude": 113.3824
  },
  {
    "id": "kalimantan-selatan",
    "nama": "Kalimantan Selatan",
    "provinsi": "Kalimantan Selatan",
    "wilayah": "Kalimantan",
    "umr": 3149977,
    "sewaTempat": 800000,
    "utilitas": 370000,
    "retribusi": 75000,
    "latitude": -3.0926,
    "longitude": 115.2838
  },
  {
    "id": "kalimantan-timur",
    "nama": "Kalimantan Timur",
    "provinsi": "Kalimantan Timur",
    "wilayah": "Kalimantan",
    "umr": 3360067,
    "sewaTempat": 950000,
    "utilitas": 420000,
    "retribusi": 90000,
    "latitude": 0.5387,
    "longitude": 116.4194
  },
  {
    "id": "kalimantan-utara",
    "nama": "Kalimantan Utara",
    "provinsi": "Kalimantan Utara",
    "wilayah": "Kalimantan",
    "umr": 3361653,
    "sewaTempat": 900000,
    "utilitas": 400000,
    "retribusi": 85000,
    "latitude": 3.0731,
    "longitude": 116.0413
  },
  {
    "id": "sulawesi-utara",
    "nama": "Sulawesi Utara",
    "provinsi": "Sulawesi Utara",
    "wilayah": "Sulawesi",
    "umr": 3545000,
    "sewaTempat": 750000,
    "utilitas": 350000,
    "retribusi": 70000,
    "latitude": 0.6246,
    "longitude": 123.975
  },
  {
    "id": "sulawesi-tengah",
    "nama": "Sulawesi Tengah",
    "provinsi": "Sulawesi Tengah",
    "wilayah": "Sulawesi",
    "umr": 2914583,
    "sewaTempat": 700000,
    "utilitas": 330000,
    "retribusi": 65000,
    "latitude": -1.43,
    "longitude": 121.4456
  },
  {
    "id": "sulawesi-selatan",
    "nama": "Sulawesi Selatan",
    "provinsi": "Sulawesi Selatan",
    "wilayah": "Sulawesi",
    "umr": 3434298,
    "sewaTempat": 800000,
    "utilitas": 370000,
    "retribusi": 75000,
    "latitude": -3.6687,
    "longitude": 119.974
  },
  {
    "id": "sulawesi-tenggara",
    "nama": "Sulawesi Tenggara",
    "provinsi": "Sulawesi Tenggara",
    "wilayah": "Sulawesi",
    "umr": 2885964,
    "sewaTempat": 680000,
    "utilitas": 320000,
    "retribusi": 65000,
    "latitude": -4.1457,
    "longitude": 122.1746
  },
  {
    "id": "sulawesi-barat",
    "nama": "Sulawesi Barat",
    "provinsi": "Sulawesi Barat",
    "wilayah": "Sulawesi",
    "umr": 2914583,
    "sewaTempat": 650000,
    "utilitas": 300000,
    "retribusi": 60000,
    "latitude": -2.8441,
    "longitude": 119.232
  },
  {
    "id": "gorontalo",
    "nama": "Gorontalo",
    "provinsi": "Gorontalo",
    "wilayah": "Sulawesi",
    "umr": 3025100,
    "sewaTempat": 650000,
    "utilitas": 300000,
    "retribusi": 60000,
    "latitude": 0.5435,
    "longitude": 123.0585
  },
  {
    "id": "maluku",
    "nama": "Maluku",
    "provinsi": "Maluku",
    "wilayah": "Maluku",
    "umr": 3141700,
    "sewaTempat": 650000,
    "utilitas": 300000,
    "retribusi": 60000,
    "latitude": -3.2385,
    "longitude": 130.1453
  },
  {
    "id": "maluku-utara",
    "nama": "Maluku Utara",
    "provinsi": "Maluku Utara",
    "wilayah": "Maluku",
    "umr": 3200000,
    "sewaTempat": 650000,
    "utilitas": 300000,
    "retribusi": 60000,
    "latitude": 1.5709,
    "longitude": 127.8088
  },
  {
    "id": "papua",
    "nama": "Papua",
    "provinsi": "Papua",
    "wilayah": "Papua",
    "umr": 4024270,
    "sewaTempat": 750000,
    "utilitas": 350000,
    "retribusi": 70000,
    "latitude": -4.2699,
    "longitude": 138.0804
  },
  {
    "id": "papua-barat",
    "nama": "Papua Barat",
    "provinsi": "Papua Barat",
    "wilayah": "Papua",
    "umr": 3600000,
    "sewaTempat": 700000,
    "utilitas": 320000,
    "retribusi": 65000,
    "latitude": -1.3361,
    "longitude": 133.1747
  },
  {
    "id": "papua-pegunungan",
    "nama": "Papua Pegunungan",
    "provinsi": "Papua Pegunungan",
    "wilayah": "Papua",
    "umr": 3869778,
    "sewaTempat": 650000,
    "utilitas": 300000,
    "retribusi": 60000,
    "latitude": -3.9777,
    "longitude": 138.4633
  },
  {
    "id": "papua-tengah",
    "nama": "Papua Tengah",
    "provinsi": "Papua Tengah",
    "wilayah": "Papua",
    "umr": 3832033,
    "sewaTempat": 650000,
    "utilitas": 300000,
    "retribusi": 60000,
    "latitude": -3.5456,
    "longitude": 136.8764
  },
  {
    "id": "papua-selatan",
    "nama": "Papua Selatan",
    "provinsi": "Papua Selatan",
    "wilayah": "Papua",
    "umr": 3950000,
    "sewaTempat": 680000,
    "utilitas": 310000,
    "retribusi": 62000,
    "latitude": -7.0128,
    "longitude": 140.416
  },
  {
    "id": "papua-barat-daya",
    "nama": "Papua Barat Daya",
    "provinsi": "Papua Barat Daya",
    "wilayah": "Papua",
    "umr": 3750000,
    "sewaTempat": 670000,
    "utilitas": 305000,
    "retribusi": 61000,
    "latitude": -2.533,
    "longitude": 132.3024
  }
];
